# Most Create db_user and password 123456
development:
  adapter: postgresql
  encoding: unicode
  database: pi_development
  pool: 5
  username: db_user
  password: 123456

test:
  adapter: postgresql
  encoding: unicode
  database: pi_test
  pool: 5
  username: db_user
  password: 123456